# Generated by Django 2.0.9 on 2018-10-06 01:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
