# Generated by Django 2.0.9 on 2018-10-04 23:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliopage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='portal_cards',
            field=wagtail.core.fields.StreamField([('portal_card', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock())), ('image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False))]))], default=''),
            preserve_default=False,
        ),
    ]
