# Generated by Django 2.0.9 on 2018-10-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfoliopage_portal_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='portal_cards',
        ),
    ]
