# Generated by Django 2.0.9 on 2018-10-05 01:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfoliopage_portal_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='portfolio_cards',
            field=wagtail.core.fields.StreamField([('portfolio_cards', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('technologies', wagtail.core.blocks.CharBlock(required=False))]))], default=''),
            preserve_default=False,
        ),
    ]
