# Generated by Django 2.0.9 on 2018-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfoliopage_portfolio_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='headline',
            field=models.CharField(default='Web Development Portfolio', max_length=255),
            preserve_default=False,
        ),
    ]
