# Generated by Django 2.0.13 on 2019-12-08 20:24

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181012_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='portal_cards',
        ),
        migrations.AddField(
            model_name='homepage',
            name='pagetitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('image_info_section', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))]),
        ),
    ]
