# Generated by Django 2.2.1 on 2019-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181027_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to the original source'),
        ),
    ]
